export { default as Boxes } from './boxes.js'
export { default as DemoAmmo } from './demoAmmo.js'
export { default as DirectionLight } from './directionLight.js'
export { default as Floor } from './floor.js'
export { default as GunPistol } from './gunPistol.js'
export { default as Skybox } from './skybox.js'
export { default as RightHand } from './rightHand.js'
