export { default as Boxes } from './boxes.js'
export { default as DirectionLight } from './directionLight.js'
export { default as Floor } from './floor.js'
// export { default as Weapon } from './weapon.js'
export { default as Skybox } from './skybox.js'
// export { default as RightHand } from './rightHand.js'
export { default as Player } from './player.js'
// export { default as AnotherPlayer } from './anotherPlayer.js'
export { default as Walls } from './walls/walls.js'
